spring:
  application:
    name: bus-tickets
  datasource:
    url: jdbc:postgresql://localhost:5432/bus_tickets
    username: bustickets
    password: bustickets
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn

time-api:
  base-url: https://timeapi.io
  update-delay-ms: 300000
